### ISSUE TITLE
current_user.is_anonymous is not callable on Part 2

### ISSUE THREAD

**Issue by FeralBytes** [mjhea0/flask-tracking#6]
```
File ".../tracking/views.py", line 15, in index
    if not current_user.is_anonymous():
TypeError: 'bool' object is not callable```


```
File ".../templates/layout.html", line 14, in top-level template code
    {% if current_user.is_anonymous() %}
AttributeError: 'bool' object has no attribute '__call__'```

**Comment by mjhea0** [comment]
You'll need to downgrade Flask-Login to the version used in the tutorial.
